version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

  webserver:
    user: root
    image: airflow_python:latest
    build: 
      context: ./
      dockerfile: Dockerfile
    #  args:
    #    AIRFLOW_DEPS: gcp_api,s3
    #    PYTHON_DEPS: sqlalchemy==1.2.0
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - FERNET_KEY=jsDPRErfv8Z_eVTnGfF8ywd19j4pyqE3NpdUBA_oRTo=
    volumes:
      - .:/usr/local/airflow
      - .:/root/airflow
    ports:
      - "8080:8080"
    
    command: bash -c "airflow webserver"
    #entrypoint: ./scripts/entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
